
package br.com.bradseg.siaw.antecipaparcela.webservice.stub;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.10
 * 2015-10-20T12:02:05.170-02:00
 * Generated source version: 2.7.10
 */

@WebFault(name = "BusinessException", targetNamespace = "http://webservice.antecipaparcela.siaw.bradseg.com.br/")
public class BusinessException_Exception extends Exception {
    
    private br.com.bradseg.siaw.antecipaparcela.webservice.stub.BusinessException businessException;

    public BusinessException_Exception() {
        super();
    }
    
    public BusinessException_Exception(String message) {
        super(message);
    }
    
    public BusinessException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public BusinessException_Exception(String message, br.com.bradseg.siaw.antecipaparcela.webservice.stub.BusinessException businessException) {
        super(message);
        this.businessException = businessException;
    }

    public BusinessException_Exception(String message, br.com.bradseg.siaw.antecipaparcela.webservice.stub.BusinessException businessException, Throwable cause) {
        super(message, cause);
        this.businessException = businessException;
    }

    public br.com.bradseg.siaw.antecipaparcela.webservice.stub.BusinessException getFaultInfo() {
        return this.businessException;
    }
}
